import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Layout from '@/components/Layout'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {


  const handleSubmit = (e) => {
    e.preventDefault();
  
    const user = {
      email,
      password,
    }
    console.log(user)
  }


  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  return (
    <>
      <Head>
        <title>Visitantes</title>
         <meta name="description" content="Generated by create next app" />
         <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 md:pt-16 sm:pt-8">

          <div className='flex items-center flex-col justify-center'>
            <span className="text-4xl mb-4">&#128591;</span>
            <h3 className="font-bold">Olá, faça login.</h3>
         </div>
        
          <div className="justify-center">
            <form className="flex items-center flex-col mt-4" onSubmit={handleSubmit}>
              <input 
                type="email" 
                name="email" 
                placeholder="e-mail@exemplo.com"
                onChange={(e) => setEmail(e.target.value)}
                // value={email || ""}  
                className='mt-1 block w-96 lg:w-80 md:w-60 xs:w-32 px-3 py-2 bg-white border border-slate-300 rounded-md text-sm shadow-sm placeholder-slate-400
                focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500
                disabled:bg-slate-50 disabled:text-slate-500 disabled:border-slate-200 disabled:shadow-none
                invalid:border-pink-500 invalid:text-pink-600
                focus:invalid:border-pink-500 focus:invalid:ring-pink-500'
              />

              <input 
                type="password" 
                name="password" 
                placeholder="senha.."
                onChange={(e) => setPassword(e.target.value)}
                // value={password || ""} 
                className='mt-4 block w-96 lg:w-80 md:w-60 xs:w-32 px-3 py-2 bg-white border border-slate-300 rounded-md text-sm shadow-sm placeholder-slate-400'   
                />

              <input 
                type="submit" 
                name="submit" 
                value="Entrar"
                className={`mt-4 block w-96 lg:w-80 md:w-60 xs:w-32 px-3 py-2  bg-lime-900 hover:bg-lime-700 cursor-pointer text-light rounded-md shadow-lg`} 
              />
            </form>
          </div>
        </Layout>
      </main>
    </>
  )
}
